-- ================================
-- SALES DATA ANALYSIS PROJECT
-- ================================

-- View dataset
SELECT *
FROM sales_data;

-- 1. Average transaction value
-- Insight: Measures typical customer spending behavior
SELECT AVG(sales) AS avg_transaction_value
FROM sales_data;

-- 2. Total revenue
-- Insight: Total revenue generated by the business
SELECT SUM(sales) AS total_revenue
FROM sales_data;

-- 3. Total number of transactions
SELECT COUNT(*) AS total_transactions
FROM sales_data;

-- 4. Highest transaction value
SELECT MAX(sales) AS highest_transaction
FROM sales_data;

-- 5. Lowest transaction value
SELECT MIN(sales) AS lowest_transaction
FROM sales_data;

-- 6. High-value transactions (above average)
-- Insight: Identifies larger purchases
SELECT COUNT(*) AS high_value_transactions
FROM sales_data
WHERE sales > 3000;
